#!/usr/bin/env node

/**
 * Environment Synchronization Script
 * 
 * This script helps synchronize environment variables from the root .env file
 * to the individual project directories that need them.
 * 
 * Usage:
 *   node sync-env.js
 *   node sync-env.js --frontend-only
 *   node sync-env.js --contracts-only
 */

const fs = require('fs');
const path = require('path');

// Configuration
const ROOT_ENV_PATH = path.join(__dirname, '.env');
const FRONTEND_ENV_PATH = path.join(__dirname, 'frontend', '.env');
const CONTRACTS_ENV_PATH = path.join(__dirname, 'contracts', '.env');

// Environment variable mappings
const FRONTEND_VARS = [
  'REACT_APP_ENV',
  'REACT_APP_VERSION',
  'REACT_APP_API_URL',
  'REACT_APP_API_TIMEOUT',
  'REACT_APP_SUPABASE_URL',
  'REACT_APP_SUPABASE_ANON_KEY',
  'REACT_APP_ETHEREUM_RPC_URL',
  'REACT_APP_CONTRACT_ADDRESS',
  'REACT_APP_CHAIN_ID',
  'REACT_APP_RECALL_CONTRACT_ADDRESS',
  'REACT_APP_COUNTERFEIT_CONTRACT_ADDRESS',
  'REACT_APP_WS_URL',
  'REACT_APP_CHAIN_NAME',
  'REACT_APP_RPC_URL',
  'REACT_APP_DEBUG',
  'REACT_APP_PORT',
  'REACT_APP_HOST',
  'SKIP_PREFLIGHT_CHECK',
  'TSC_COMPILE_ON_ERROR',
  'DISABLE_ESLINT_PLUGIN',
  'ESLINT_NO_DEV_ERRORS',
  'CI',
  'BROWSER',
  'PORT',
  'HOST',
  'HTTPS'
];

const CONTRACTS_VARS = [
  'ETHEREUM_RPC_URL',
  'ETHEREUM_RPC_URL_SEPOLIA',
  'ETHEREUM_RPC_URL_MAINNET',
  'SEPOLIA_RPC_URL',
  'PRIVATE_KEY',
  'CONTRACT_ADDRESS',
  'RECALL_CONTRACT_ADDRESS',
  'COUNTERFEIT_CONTRACT_ADDRESS',
  'MANUFACTURER_ADDRESS',
  'INVESTIGATOR_ADDRESS',
  'INFURA_PROJECT_ID',
  'ALCHEMY_API_KEY',
  'ETHERSCAN_API_KEY',
  'HARDHAT_NETWORK'
];

// Backend variables (for backend .env)
const BACKEND_VARS = [
  'NODE_ENV',
  'PORT',
  'API_PORT',
  'CORS_ORIGIN',
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_JWT_SECRET',
  'SUPABASE_PROJECT_ID',
  'SUPABASE_DB_PASSWORD',
  'DATABASE_URL',
  'ETHEREUM_RPC_URL',
  'PRIVATE_KEY',
  'INFURA_PROJECT_ID',
  'HARDHAT_NETWORK',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'AWS_S3_BUCKET',
  'EC2_INSTANCE_ID',
  'EC2_PUBLIC_DNS',
  'EC2_PUBLIC_IP',
  'JWT_SECRET',
  'SESSION_SECRET',
  'JWT_EXPIRY'
];

// Additional environment variables that should be preserved
const ADDITIONAL_VARS = [
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'AWS_S3_BUCKET',
  'EC2_INSTANCE_ID',
  'EC2_PUBLIC_DNS',
  'EC2_PUBLIC_IP',
  'NODE_ENV',
  'PORT',
  'API_PORT',
  'CORS_ORIGIN',
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'DATABASE_URL',
  'SUPABASE_JWT_SECRET',
  'SUPABASE_PROJECT_ID',
  'SUPABASE_DB_PASSWORD',
  'JWT_SECRET',
  'SESSION_SECRET',
  'JWT_EXPIRY',
  'PHARBIT_PEM_KEY'
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  Environment file not found: ${filePath}`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const envVars = {};
  
  content.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  
  return envVars;
}

function writeEnvFile(filePath, envVars, comment = '') {
  const lines = [];
  
  if (comment) {
    lines.push(comment);
    lines.push('# This file is automatically generated from the root .env file');
    lines.push('# Do not edit this file directly - edit /workspace/.env instead');
    lines.push('');
  }
  
  Object.entries(envVars).forEach(([key, value]) => {
    lines.push(`${key}=${value}`);
  });
  
  fs.writeFileSync(filePath, lines.join('\n') + '\n');
}

function syncAllEnv() {
  console.log('🔄 Syncing all environment variables...');
  
  // Read the root .env file but don't modify it
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  
  // Continue with frontend/contracts specific syncs
}

function syncFrontendEnv() {
  console.log('🔄 Syncing frontend environment variables...');
  
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  const frontendEnv = {};
  // helper defaults
  const apiPort = rootEnv.API_PORT || rootEnv.PORT || '3001';
  const frontendPort = rootEnv.REACT_APP_PORT || rootEnv.PORT || '3000';
  const isCodespaces = process.env.CODESPACE_NAME || process.env.GITHUB_CODESPACE_NAME || process.env.CODESPACES;
  // attempt to derive a Codespaces preview host if running in Codespaces
  let codespaceHost = null;
  if (process.env.CODESPACE_NAME) codespaceHost = process.env.CODESPACE_NAME;
  if (!codespaceHost && process.env.GITHUB_CODESPACE_NAME) codespaceHost = process.env.GITHUB_CODESPACE_NAME;

  FRONTEND_VARS.forEach(varName => {
    if (rootEnv[varName]) {
      frontendEnv[varName] = rootEnv[varName];
      return;
    }

    // Auto-fill sensible defaults for commonly missing frontend vars
    switch (varName) {
      case 'REACT_APP_API_URL':
        if (codespaceHost) {
          frontendEnv[varName] = `https://${codespaceHost}-${apiPort}.app.github.dev/api`;
        } else {
          frontendEnv[varName] = `http://localhost:${apiPort}/api`;
        }
        break;
      case 'REACT_APP_WS_URL':
        if (codespaceHost) {
          frontendEnv[varName] = `wss://${codespaceHost}-${apiPort}.app.github.dev/ws`;
        } else {
          frontendEnv[varName] = `ws://localhost:${apiPort}/ws`;
        }
        break;
      case 'REACT_APP_ETHEREUM_RPC_URL':
      case 'REACT_APP_RPC_URL':
        frontendEnv[varName] = rootEnv.ETHEREUM_RPC_URL || 'http://localhost:8545';
        break;
      case 'REACT_APP_CHAIN_ID':
        frontendEnv[varName] = rootEnv.CHAIN_ID || '1337';
        break;
      case 'REACT_APP_CHAIN_NAME':
        frontendEnv[varName] = rootEnv.CHAIN_NAME || 'Localhost';
        break;
      case 'REACT_APP_CONTRACT_ADDRESS':
      case 'REACT_APP_RECALL_CONTRACT_ADDRESS':
      case 'REACT_APP_COUNTERFEIT_CONTRACT_ADDRESS':
        frontendEnv[varName] = rootEnv.CONTRACT_ADDRESS || '0x0000000000000000000000000000000000000000';
        break;
      case 'REACT_APP_API_TIMEOUT':
        frontendEnv[varName] = rootEnv.REACT_APP_API_TIMEOUT || '10000';
        break;
      case 'REACT_APP_ENV':
        frontendEnv[varName] = rootEnv.NODE_ENV || 'development';
        break;
      case 'REACT_APP_VERSION':
        frontendEnv[varName] = rootEnv.REACT_APP_VERSION || '0.0.0';
        break;
      case 'REACT_APP_PORT':
      case 'PORT':
        frontendEnv[varName] = frontendPort;
        break;
      case 'HOST':
      case 'REACT_APP_HOST':
        frontendEnv[varName] = rootEnv.HOST || 'localhost';
        break;
      case 'HTTPS':
        frontendEnv[varName] = rootEnv.HTTPS || 'false';
        break;
      default:
        // For other vars, supply empty string so the frontend can still start
        frontendEnv[varName] = '';
        console.warn(`⚠️  Frontend variable ${varName} not found in root .env — defaulting to empty string`);
    }
  });
  
  writeEnvFile(FRONTEND_ENV_PATH, frontendEnv, '# Frontend Environment Variables');
  console.log(`✅ Frontend .env updated: ${FRONTEND_ENV_PATH}`);
}

function syncContractsEnv() {
  console.log('🔄 Syncing contracts environment variables...');
  
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  const contractsEnv = {};
  
  CONTRACTS_VARS.forEach(varName => {
    if (rootEnv[varName]) {
      contractsEnv[varName] = rootEnv[varName];
    } else {
      console.warn(`⚠️  Contracts variable ${varName} not found in root .env`);
    }
  });
  
  writeEnvFile(CONTRACTS_ENV_PATH, contractsEnv, '# Contracts Environment Variables');
  console.log(`✅ Contracts .env updated: ${CONTRACTS_ENV_PATH}`);
}

function syncBackendEnv() {
  console.log('🔄 Syncing backend environment variables...');
  
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  const backendEnv = {};
  
  BACKEND_VARS.forEach(varName => {
    if (rootEnv[varName]) {
      backendEnv[varName] = rootEnv[varName];
    } else {
      console.warn(`⚠️  Backend variable ${varName} not found in root .env`);
    }
  });
  
  const backendEnvPath = path.join(__dirname, 'backend', '.env');
  writeEnvFile(backendEnvPath, backendEnv, '# Backend Environment Variables');
  console.log(`✅ Backend .env updated: ${backendEnvPath}`);
}

// Main execution
syncAllEnv(); // Always sync all variables first

if (process.argv.includes('--frontend-only')) {
  syncFrontendEnv();
} else if (process.argv.includes('--contracts-only')) {
  syncContractsEnv();
} else if (process.argv.includes('--backend-only')) {
  syncBackendEnv();
} else {
  syncFrontendEnv();
  syncContractsEnv();
  syncBackendEnv();
}

function main() {
  const args = process.argv.slice(2);
  
  console.log('🚀 Environment Synchronization Script');
  console.log('=====================================\n');
  
  if (!fs.existsSync(ROOT_ENV_PATH)) {
    console.error('❌ Root .env file not found. Please create /workspace/.env first.');
    process.exit(1);
  }
  
  if (args.includes('--frontend-only')) {
    syncFrontendEnv();
  } else if (args.includes('--contracts-only')) {
    syncContractsEnv();
  } else if (args.includes('--backend-only')) {
    syncBackendEnv();
  } else {
    syncFrontendEnv();
    syncContractsEnv();
    syncBackendEnv();
  }
  
  console.log('\n✨ Environment synchronization complete!');
  console.log('\n📝 All environment variables have been synchronized to their respective directories.');
}

if (require.main === module) {
  main();
}

module.exports = {
  syncFrontendEnv,
  syncContractsEnv,
  syncBackendEnv,
  parseEnvFile,
  writeEnvFile
};