#!/usr/bin/env node

/**
 * Environment Synchronization Script
 * 
 * This script helps synchronize environment variables from the root .env file
 * to the individual project directories that need them.
 * 
 * Usage:
 *   node sync-env.js
 *   node sync-env.js --frontend-only
 *   node sync-env.js --contracts-only
 */

const fs = require('fs');
const path = require('path');

// Configuration
const ROOT_ENV_PATH = path.join(__dirname, '.env');
const FRONTEND_ENV_PATH = path.join(__dirname, 'frontend', '.env');
const CONTRACTS_ENV_PATH = path.join(__dirname, 'contracts', '.env');

// Environment variable mappings
const FRONTEND_VARS = [
  'REACT_APP_ENV',
  'REACT_APP_VERSION',
  'REACT_APP_API_URL',
  'REACT_APP_API_TIMEOUT',
  'REACT_APP_SUPABASE_URL',
  'REACT_APP_SUPABASE_ANON_KEY',
  'REACT_APP_ETHEREUM_RPC_URL',
  'REACT_APP_CONTRACT_ADDRESS',
  'REACT_APP_CHAIN_ID',
  'REACT_APP_RECALL_CONTRACT_ADDRESS',
  'REACT_APP_COUNTERFEIT_CONTRACT_ADDRESS'
];

const CONTRACTS_VARS = [
  'ETHEREUM_RPC_URL',
  'ETHEREUM_RPC_URL_SEPOLIA',
  'ETHEREUM_RPC_URL_MAINNET',
  'SEPOLIA_RPC_URL',
  'PRIVATE_KEY',
  'CONTRACT_ADDRESS',
  'RECALL_CONTRACT_ADDRESS',
  'COUNTERFEIT_CONTRACT_ADDRESS',
  'MANUFACTURER_ADDRESS',
  'INVESTIGATOR_ADDRESS',
  'INFURA_PROJECT_ID',
  'ALCHEMY_API_KEY',
  'ETHERSCAN_API_KEY'
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  Environment file not found: ${filePath}`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const envVars = {};
  
  content.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  
  return envVars;
}

function writeEnvFile(filePath, envVars, comment = '') {
  const lines = [];
  
  if (comment) {
    lines.push(comment);
    lines.push('# This file is automatically generated from the root .env file');
    lines.push('# Do not edit this file directly - edit /workspace/.env instead');
    lines.push('');
  }
  
  Object.entries(envVars).forEach(([key, value]) => {
    lines.push(`${key}=${value}`);
  });
  
  fs.writeFileSync(filePath, lines.join('\n') + '\n');
}

function syncFrontendEnv() {
  console.log('🔄 Syncing frontend environment variables...');
  
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  const frontendEnv = {};
  
  FRONTEND_VARS.forEach(varName => {
    if (rootEnv[varName]) {
      frontendEnv[varName] = rootEnv[varName];
    } else {
      console.warn(`⚠️  Frontend variable ${varName} not found in root .env`);
    }
  });
  
  writeEnvFile(FRONTEND_ENV_PATH, frontendEnv, '# Frontend Environment Variables');
  console.log(`✅ Frontend .env updated: ${FRONTEND_ENV_PATH}`);
}

function syncContractsEnv() {
  console.log('🔄 Syncing contracts environment variables...');
  
  const rootEnv = parseEnvFile(ROOT_ENV_PATH);
  const contractsEnv = {};
  
  CONTRACTS_VARS.forEach(varName => {
    if (rootEnv[varName]) {
      contractsEnv[varName] = rootEnv[varName];
    } else {
      console.warn(`⚠️  Contracts variable ${varName} not found in root .env`);
    }
  });
  
  writeEnvFile(CONTRACTS_ENV_PATH, contractsEnv, '# Contracts Environment Variables');
  console.log(`✅ Contracts .env updated: ${CONTRACTS_ENV_PATH}`);
}

function main() {
  const args = process.argv.slice(2);
  
  console.log('🚀 Environment Synchronization Script');
  console.log('=====================================\n');
  
  if (!fs.existsSync(ROOT_ENV_PATH)) {
    console.error('❌ Root .env file not found. Please create /workspace/.env first.');
    process.exit(1);
  }
  
  if (args.includes('--frontend-only')) {
    syncFrontendEnv();
  } else if (args.includes('--contracts-only')) {
    syncContractsEnv();
  } else {
    syncFrontendEnv();
    syncContractsEnv();
  }
  
  console.log('\n✨ Environment synchronization complete!');
  console.log('\n📝 Note: Backend loads environment variables directly from root .env');
  console.log('   No separate .env file needed for backend.');
}

if (require.main === module) {
  main();
}

module.exports = {
  syncFrontendEnv,
  syncContractsEnv,
  parseEnvFile,
  writeEnvFile
};